services:
  mysql:
    image: mysql:8.3
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bootstrap/db-init:/docker-entrypoint-initdb.d
      - ./bootstrap/ensure-db.sh:/docker-healthcheck.sh
    healthcheck:
      test: ["CMD", "bash", "/docker-healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: ./hibernate-projet/
      dockerfile: App.dockerfile
    container_name: app
    depends_on:
      - mysql
    restart: on-failure
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8080:8080"

  api-consumer:
    build:
      context: ./api-consumer/
      dockerfile: Dockerfile
    container_name: api-consumer
    depends_on:
      - app
    restart: on-failure

  seeding:
    build:
      context: ./hibernate-projet/
      dockerfile: Seeding.dockerfile
    container_name: seeding
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password
  


volumes:
  mysql_data:
    



