services:
  test-mysql:
    image: mysql:8.3
    container_name: test-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - test-mysql_data:/var/lib/mysql

  test-runner:
    container_name: test-runner
    build:
      context: ./hibernate-projet/
      dockerfile: App.dockerfile
      target: build
    command:
      - mvn
      - test
    depends_on:
      - test-mysql
    volumes:
      - ./hibernate-projet:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password

volumes:
  test-mysql_data:
# Run command: docker compose -f docker-compose.yml -f docker-compose.test.yml up test-runner